### ISSUE TITLE
Netlogging

### ISSUE THREAD

**Issue by ghost** [bumptech/montage#2]
We need to provide support for the LogCallback function (argument to runDaemon) because it's non-trivial to ensure that netlog calls don't write interspersedly.

**Comment by wmoss** [comment]
Presumably not everyone is using the same logging mechanism we are. The idea was that they could provide their own logging function (that interfaced with whatever their logging infrastructure was) and the library would just call it. Perhaps it's not as general or easy to use as it should be though :)

**Comment by ghost** [comment]
Right now the example code actually outputs logs using non-STM protected writes, because a large log architecture to test logic ratio would be confusing/silly; this made me think about how much of a barrier the LogCallback is.

**Comment by wmoss** [comment]
Now that we're setting line buffering in Montage and have a decent example of how to use this, I think we're okay.
