### ISSUE TITLE
Protocol Buffers

### ISSUE THREAD

**Issue by ghost** [bumptech/montage#3]
Right now the user is forced to only store protocol-buffers in Riak if relying on montage.  I don't think this is reasonable.  An extra function in the MontageRiakValue class on deserialization in serveMontageZmq I think would do the job of generalizing this out.  Since the MontageEnvelope itself only requires a ByteString as its data', everything else (I think) is good.

**Comment by wmoss** [comment]
I'm not sure I follow. Where is data' treated as anything by a ByteString?

**Comment by wmoss** [comment]
@erin added an example, so I think we're all good.

**Comment by erin** [comment]
Hello,

I think you might have the wrong email address for your project notifications - I'm a different Erin Bourne. Sorry! Just didn't want to get any private information or for the other Erin to miss something important!

Thanks,
Erin Bourne (in Red Deer, Alberta)

**Comment by wmoss** [comment]
My bad, sorry!
